### ISSUE TITLE
Demo example tutorial

### ISSUE THREAD

**Issue by JoseGomesJPG** [facebookincubator/momentum#82]
Hello. I'm trying to run the "Monocular RGB Body Tracking Solver" example that is on the webpage. I managed to build Momentum and I can open the viewers (c3d, fbx and glb) and get 02_01.c3d to load and run. However, I can't seem to find the resources to run the examples on the website. Could you point me in the right direction? Thank you.

**Comment by jeongseok-meta** [comment]
Hello @JoseGomesJPG! Thank you for trying to run the examples. We are currently in the process of releasing resources soon, including character model files and motion data. In the meantime, only the [examples](https://github.com/facebookincubator/momentum/tree/main/momentum/examples) ([webpages](https://facebookincubator.github.io/momentum/docs/examples/viewers)) will be available,but not the ones on the front page of the website. Please stay tuned!

**Comment by jeongseok-meta** [comment]
Closing for now. Feel free to reopen if you have any further issues!

**Comment by JoseGomesJPG** [comment]
I see. Thank you for your response. For now I'll focus on the examples you linked then.
I can run the viewer examples. I'm trying to run the process markers example, but I don't have these files, listed in the .config file

model = "../models/character_s0.fbx"
parameters = "../models/character_mocap.model"
locators = "../models/optitrack_biomech57.locators"

Will you be releasing them soon?
Thanks :)

**Comment by jeongseok-meta** [comment]
Yes, those files are part of the data release we're aiming for. The timeline is still TBD, but we're working on it!

**Comment by SineadBeyondCapture** [comment]
https://github.com/facebookresearch/MHR does not contain a .locators file, unless I am just not seeing it assets folder. Do you plan to release it?
